### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by AniCatPro** [Philipp0002/XADGPS-Client#1]
Hello,

When entering correct account credentials, the application crashes and returns to the main screen. I am using the "Login2" method since I use IMEI (loginAsync.paramLoginType = "1"). I tried logging in via OpenAPIv4 at [this URL](https://appapi.xadgps.com/openapiv4.asmx?op=Login2) (user, password, 1, 25, EN) and received the correct string value (and 
jsonText).

I am compiling in Android Studio with API level 35.

I also tried changing the login type (paramLoginType), but the error persists

LOG
<img width="1480" alt="Снимок экрана 2024-07-29 в 16 50 53" src="https://github.com/user-attachments/assets/3d8742c8-124b-402c-bc7a-0403b711b0c4">

**Comment by AniCatPro** [comment]
Can you upload the APK file to Releases? maybe I'm doing something wrong.

**Comment by Philipp0002** [comment]
I'm trying to recreate your setup. What credentials do you use to log-in? Do you use your IMEI as Username?

TBH: I have never tried signing in with IMEI

**Comment by Philipp0002** [comment]
I think that I found the answer to the problem in the source code of the official XADGPS-App:

![grafik](https://github.com/user-attachments/assets/66b58b7f-bcdc-4d91-8c0c-40c33b1d2fb2)

The server sends a different response-schema based on the LoginType. So when you login using your username+password you get a different type of response compared to when you login using IMEI.

**Comment by Philipp0002** [comment]
I'm currently working on a fix. I will notify you as soon as I get it working,

**Comment by Philipp0002** [comment]
@AniCatPro I've fixed the bug. Please checkout the branch named "usage-without-account" or pull from "master". When installing on your phone, make sure you have cleared all the apps data beforehand.

**Comment by AniCatPro** [comment]
@Philipp0002 Everything worked out. Operational work! Thanks
